### ISSUE TITLE
ST background color not matching color in website

### ISSUE THREAD

**Issue by zhengpd** [monokai-pro/sublime-text#180]
Hi, Monokai Pro looks amazing.

The background color of "Monokai Pro Light (Filter Sun)" in ST is `#FAEFE6`, which is different with the color in website. Version 2.0.2.

The bg of VSCode is fine, which is `#F8EFE7`. Also version 2.0.2.

**Comment by Monokai** [comment]
How did you get the background color of the version in Sublime Text?

**Comment by zhengpd** [comment]
> How did you get the background color of the version in Sublime Text?

I picked the color via ColorSnapper2. Monokai Pro is the only theme installed.

Sublime Text Build 4180.

**Comment by zhengpd** [comment]
It might be something to fixed by Sublime Text team, not Monokai Pro. Wezterm had similar issue. I set background to `#F8EFE7` but Wezterm renders bg as `#FAEFE6`. Wezterm fixed the issue in nightly version, see https://github.com/wez/wezterm/pull/6063.
