### ISSUE TITLE
macOS Terminal.app Support 

### ISSUE THREAD

**Issue by darqueos** [monokai-pro/sublime-text#45]
Hello! Huge fan of what you created. So much that I wish I could use it across all my IDEs and the main **terminal**. Any plans for a `Monokai Pro.terminal` version?

**Comment by ntwb** [comment]
I updated my terminal to use Monokai Pro, happy to share that if that's ok by @Monokai 

I also use Fish shell rather than Bash, happy to also share the Monokai Pro colour config I use in my Fish shell theme also.

**Comment by Monokai** [comment]
Psst…

http://packages.monokai.pro/terminal/monokai-pro-terminal.zip
http://packages.monokai.pro/iterm/monokai-pro-iterm.zip

These are beta packages, I have to test some more before showing them on www.monokai.pro

@ntwb yeah, you can always share your configs of course!

**Comment by ntwb** [comment]
Awesome @Monokai 

One thing I have with my scheme is I created a "blue" colour to use as "blue" rather than the "orange" you're using in it's place, I did this as I spend a considerable amount of time in my terminal and quite often the "orange" would cause readability concerns.

The blue I use is #6088ff, it came from one of those color _triad_ generators, it's generated from the _red #fe6188_ and the _green #a9dc76_ from memory.

I also use [Fish](http://fish.sh/), rather than Bash for my shell, the theme I use is [Pure](https://github.com/rafaelrinaldi/pure)

Here's a quick screenshot of yours and min side-by-side, yours on the left, mine on the right:

![screen shot 2017-11-01 at 9 14 23 pm](https://user-images.githubusercontent.com/1016458/32270437-a3c04a44-bf41-11e7-970b-04bd118b04c8.png)

Looks like I've got a couple of tweaks to adjust in the colors, for some reason I've a couple of those wrong /shrug

For Fish, [color config is defined](https://github.com/rafaelrinaldi/pure#configuration) in a custom Fish config file `config.fish`, the Monokai settings I currently use and which I need to update, especially the background side of things are:
```fish
# Change the colors
set pure_color_blue (set_color "6088ff")
set pure_color_cyan (set_color "78dce8")
set pure_color_gray (set_color "6c6c6c")
set pure_color_green (set_color "a9dc76")
set pure_color_normal (set_color "000000")
set pure_color_red (set_color "fe6188")
set pure_color_yellow (set_color "ffd866")
```

**Comment by kevinrambaud** [comment]
Bump, any news about a release date of these terminal themes ? 😃

**Comment by ntwb** [comment]
@kevinrambaud The Zips are linked above, give them a try and share your feedback

**Comment by darqueos** [comment]
I've been using them for a while now, and they seem solid for me. Great work!

**Comment by kevinrambaud** [comment]
I agree, I'm using the iTerm one for a couple of days and I'm happy with it !

**Comment by othree** [comment]
Hoping for a Vim version monokai pro color theme

**Comment by ytang** [comment]
I have the same concern as @ntwb, but I don't want to introduce new colors. So I've just swapped blue (color 4 & 12) and magenta (color 5 & 13) in the color palette, and it's pretty good.

**Comment by jdsimcoe** [comment]
@Monokai I love the iTerm themes. The only thing that needs to be tweaked is the default Cursor Guide line color. I found that `#FFFFFF` with a 5% opacity matches the highlighted line color in the `Monokai Pro` VSCode themes (see screenshot reference below):

![screenshot]()

The Cursor Guide feature of iTerm can be disabled, but for those that have it on, it's nice to match the Monokai Pro theme.

**Comment by duhok1** [comment]
I am willing to port the color palette to many editors (vim, gedit) or terminals (gnome, konsole, tilix) if @Monokai allows that!

In fact, I'm using it for my personal use by now, **gedit** for example:

![Screenshot from 2019-04-10 16-03-18](https://user-images.githubusercontent.com/46654846/55909697-a9a15000-5baa-11e9-817e-96264a8dfeaf.png)

![Screenshot from 2019-04-10 16-03-48](https://user-images.githubusercontent.com/46654846/55909709-adcd6d80-5baa-11e9-975f-72e0d787906f.png)

**Comment by WangZishi** [comment]
@Monokai It seems this(http://packages.monokai.pro/iterm/monokai-pro-iterm.zip) link is broken.

**Comment by rizkysyazuli** [comment]
A bit OOT, but [Windows Terminal](https://github.com/microsoft/terminal) could use some @Monokai love as well 😉

FYI, their color schemes is just simple JSON.

```
{
    "background" : "#0C0C0C",
    "black" : "#0C0C0C",
    "blue" : "#0037DA",
    "brightBlack" : "#767676",
    "brightBlue" : "#3B78FF",
    "brightCyan" : "#61D6D6",
    "brightGreen" : "#16C60C",
    "brightPurple" : "#B4009E",
    "brightRed" : "#E74856",
    "brightWhite" : "#F2F2F2",
    "brightYellow" : "#F9F1A5",
    "cyan" : "#3A96DD",
    "foreground" : "#CCCCCC",
    "green" : "#13A10E",
    "name" : "Campbell",
    "purple" : "#881798",
    "red" : "#C50F1F",
    "white" : "#CCCCCC",
    "yellow" : "#C19C00"
}
```

**Comment by ntwb** [comment]
Just noticed this https://www.npmjs.com/package/hyper-monokai-pro

**Comment by mskrzetuski** [comment]
So anyone a good vim theme for Monokai Pro Machine?

**Comment by tabs-not-spaces** [comment]
For those Interested in setting up Monokai-Pro for Windows Terminal, I've transposed the "Monokai_Pro.terminal" theme to the Terminal colour scheme format.

```
{
    "background" : "#2d2a2e",
    "black" : "#2d2a2e",
    "blue" : "#FC9867",
    "brightBlack" : "#727072",
    "brightBlue" : "#FC9867",
    "brightCyan" : "#78DCE8",
    "brightGreen" : "#a9dc76",
    "brightPurple" : "#AB9DF2",
    "brightRed" : "#FF6188",
    "brightWhite" : "#fcfcfa",
    "brightYellow" : "#ffd866",
    "cyan" : "#78DCE8",
    "foreground" : "#fcfcfa",
    "green" : "#a9dc76",
    "name" : "Monokai-Pro",
    "purple" : "#AB9DF2",
    "red" : "#FF6188",
    "white" : "#fcfcfa",
    "yellow" : "#ffd866"
}
```

enjoy.

**Comment by Aimsucks** [comment]
I ported the colors over to ConEmu (and therefore Cmder) for any of the Windows users out there.
```xml
<key name="Palette1" modified="2020-03-24 10:40:00" build="180626">
	<value name="Name" type="string" data="Monokai Pro"/>
	<value name="TextColorIdx" type="hex" data="10"/>
	<value name="BackColorIdx" type="hex" data="10"/>
	<value name="PopTextColorIdx" type="hex" data="10"/>
	<value name="PopBackColorIdx" type="hex" data="10"/>
	<value name="ColorTable00" type="dword" data="002e2a2d"/>
	<value name="ColorTable01" type="dword" data="006798fc"/>
	<value name="ColorTable02" type="dword" data="0076dca9"/>
	<value name="ColorTable03" type="dword" data="00e8dc78"/>
	<value name="ColorTable04" type="dword" data="008861ff"/>
	<value name="ColorTable05" type="dword" data="00f29dab"/>
	<value name="ColorTable06" type="dword" data="0066d8ff"/>
	<value name="ColorTable07" type="dword" data="00fafcfc"/>
	<value name="ColorTable08" type="dword" data="00727072"/>
	<value name="ColorTable09" type="dword" data="006798fc"/>
	<value name="ColorTable10" type="dword" data="0076dca9"/>
	<value name="ColorTable11" type="dword" data="00e8dc78"/>
	<value name="ColorTable12" type="dword" data="008861ff"/>
	<value name="ColorTable13" type="dword" data="00f29dab"/>
	<value name="ColorTable14" type="dword" data="0066d8ff"/>
	<value name="ColorTable15" type="dword" data="00fafcfc"/>
</key>
```

**Comment by KevinSjoberg** [comment]
@Monokai any short term plans of making the terminal color schemes official? 🙂

**Comment by ntwb** [comment]
Looks like I need to tweak my settings:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/1016458/80341915-a0af1980-88a6-11ea-958b-9c16e38a1614.png">

**Comment by faustbrian** [comment]
@Monokai has there ever been an official release of the terminal themes?

**Comment by lzaaldian** [comment]
> Psst…
> 
> http://packages.monokai.pro/terminal/monokai-pro-terminal.zip
> http://packages.monokai.pro/iterm/monokai-pro-iterm.zip
> 
> These are beta packages, I have to test some more before showing them on [www.monokai.pro](http://www.monokai.pro)
> 
> @ntwb yeah, you can always share your configs of course!


Hi @Monokai I made a macOS Terminal.app theme from the colors in Monokai Pro for Sublime Text website.

If anyone want to give it a try, you can get it [here](https://github.com/lzaaldian/monokai-pro--terminal-app). Hope you guys like it 😬

**Comment by ntwb** [comment]
@lzaaldian Is that for Sublime Text or Sublime Merge?

**Comment by lzaaldian** [comment]
> @lzaaldian Is that for Sublime Text or Sublime Merge?

Hi, @ntwb That is theme for Terminal.app

**Comment by kdeldycke** [comment]
I personally use Monokai Soda from https://github.com/lysyi3m/macos-terminal-themes#monokai-soda-download for its increased contrast.

**Comment by xaperret** [comment]
I recently purchased a copy of monokai pro wanting to support your effort @Monokai are you still working on porting the theme on the terminal ?

**Comment by zakiaziz** [comment]
> I recently purchased a copy of monokai pro wanting to support your effort @Monokai are you still working on porting the theme on the terminal ?

You clearly didn't read the thread https://github.com/Monokai/monokai-pro-sublime-text/issues/45#issuecomment-341005595

**Comment by xaperret** [comment]
> > I recently purchased a copy of monokai pro wanting to support your effort @Monokai are you still working on porting the theme on the terminal ?
> 
> You clearly didn't read the thread [#45 (comment)](https://github.com/Monokai/monokai-pro-sublime-text/issues/45#issuecomment-341005595)

2017..

**Comment by roberrrt-s** [comment]
Yes joehoe @Monokai please terminal support ^____^

**Comment by lzaaldian** [comment]
> Yes joehoe @Monokai please terminal support ^____^

Perhaps you want to check this out https://github.com/lzaaldian/monokai-pro--terminal-app. A Monokai theme for Terminal app.

**Comment by gobijan** [comment]
@Monokai can we also have an update for the new light themes for iterm and terminal? :)

**Comment by Monokai** [comment]
@gobijan Just use the same link to the zips: https://github.com/Monokai/monokai-pro-sublime-text/issues/45#issuecomment-341005595 :)

**Comment by Monokai** [comment]
Finally got a dedicated page: https://monokai.pro/terminal
And optionally a starter config for Zsh: https://monokai.pro/zsh
